### ISSUE TITLE
Object collision still occurs with latest dedupe jobs code

### ISSUE THREAD

**Issue by wgilling** [discoverygarden/islandora_job#29]
I am still seeing islandora_job_jobs_islandora_do_derivatives being handed for the same exact object on more than one gearman worker -- usually within two seconds of the first worker starting to process the derivatives.

This is also happening intermittently - there are collisions to update the RELS-EXT for parent objects.  When this happens, the gearman-worker outputs something like this: 
WD islandora: Failed to modify datastream RELS-EXT from                [error]
pitt:31735066369491code: 409message: Conflict
The callback islandora_job_jobs_islandora_do_derivatives with args     [error]
pitt:31735066369491, Array, 3 threw an exception.
WD php: RepositoryException: Conflict in                               [error]
RepositoryConnection->parseFedoraExceptions() (line 229 of
/var/www/html/drupal-7.54_gamera_copy/sites/all/libraries/tuque/RepositoryConnection.php).
Drush command terminated abnormally due to an unrecoverable error.     [error]

On fedora, the fedora.log contains a similar exceptions related to the attempted update of the RELS-EXT.
WARN 2017-11-28 09:44:39.825 [http-bio-8080-exec-7566] (DatastreamResource) pitt:31735066369491/RELS-EXT lastModifiedDate (2017-11-28T14:44:39.75Z) is more recent than $
org.fcrepo.server.errors.DatastreamLockedException: pitt:31735066369491/RELS-EXT lastModifiedDate (2017-11-28T14:44:39.75Z) is more recent than the request (2017-11-28T$

Is it possible that two different workers both finish the page object that they are working on --- and when they query to see whether or not they were the last page object in the current batch set, the answer to both is TRUE... leading both objects to kick off an update of their parent's RELS-EXT.

**Comment by nhart** [comment]
Hi Brian, if you'd like us to look into this, please send us an email to support@discoverygarden.ca and we'll be happy to assist.

Have a good evening,
Nelson
DGI Support Team Lead

**Comment by wgilling** [comment]
I will make a pull request today with my code that fixes the dedupe issue we are seeing.

The true problem comes down to the fact that the islandora_job_job_status table is not updated until well after the dedupe check.  The dedupe check now will set that job as "working" if the job did not exist or if it was in the waiting state.

**Comment by willtp87** [comment]
@bgilling Thanks for looking into this!
